/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as StrategieRouteImport } from './routes/strategie'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as ModeleRouteImport } from './routes/modele'
import { Route as MarcheRouteImport } from './routes/marche'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategieRoute = StrategieRouteImport.update({
  id: '/strategie',
  path: '/strategie',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeleRoute = ModeleRouteImport.update({
  id: '/modele',
  path: '/modele',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcheRoute = MarcheRouteImport.update({
  id: '/marche',
  path: '/marche',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/marche': typeof MarcheRoute
  '/modele': typeof ModeleRoute
  '/solution': typeof SolutionRoute
  '/strategie': typeof StrategieRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/marche': typeof MarcheRoute
  '/modele': typeof ModeleRoute
  '/solution': typeof SolutionRoute
  '/strategie': typeof StrategieRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/marche': typeof MarcheRoute
  '/modele': typeof ModeleRoute
  '/solution': typeof SolutionRoute
  '/strategie': typeof StrategieRoute
  '/vision': typeof VisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/marche'
    | '/modele'
    | '/solution'
    | '/strategie'
    | '/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/marche'
    | '/modele'
    | '/solution'
    | '/strategie'
    | '/vision'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/marche'
    | '/modele'
    | '/solution'
    | '/strategie'
    | '/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MarcheRoute: typeof MarcheRoute
  ModeleRoute: typeof ModeleRoute
  SolutionRoute: typeof SolutionRoute
  StrategieRoute: typeof StrategieRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategie': {
      id: '/strategie'
      path: '/strategie'
      fullPath: '/strategie'
      preLoaderRoute: typeof StrategieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modele': {
      id: '/modele'
      path: '/modele'
      fullPath: '/modele'
      preLoaderRoute: typeof ModeleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marche': {
      id: '/marche'
      path: '/marche'
      fullPath: '/marche'
      preLoaderRoute: typeof MarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MarcheRoute: MarcheRoute,
  ModeleRoute: ModeleRoute,
  SolutionRoute: SolutionRoute,
  StrategieRoute: StrategieRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
