/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as PartenaireRouteImport } from './routes/partenaire'
import { Route as LogistiqueRouteImport } from './routes/logistique'
import { Route as ConditionsGeneralesRouteImport } from './routes/conditions-generales'
import { Route as CommercantsRouteImport } from './routes/commercants'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'

const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenaireRoute = PartenaireRouteImport.update({
  id: '/partenaire',
  path: '/partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const LogistiqueRoute = LogistiqueRouteImport.update({
  id: '/logistique',
  path: '/logistique',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesRoute = ConditionsGeneralesRouteImport.update({
  id: '/conditions-generales',
  path: '/conditions-generales',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercantsRoute = CommercantsRouteImport.update({
  id: '/commercants',
  path: '/commercants',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/commercants': typeof CommercantsRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/logistique': typeof LogistiqueRoute
  '/partenaire': typeof PartenaireRoute
  '/solution': typeof SolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/commercants': typeof CommercantsRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/logistique': typeof LogistiqueRoute
  '/partenaire': typeof PartenaireRoute
  '/solution': typeof SolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/commercants': typeof CommercantsRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/logistique': typeof LogistiqueRoute
  '/partenaire': typeof PartenaireRoute
  '/solution': typeof SolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/commercants'
    | '/conditions-generales'
    | '/logistique'
    | '/partenaire'
    | '/solution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/commercants'
    | '/conditions-generales'
    | '/logistique'
    | '/partenaire'
    | '/solution'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/commercants'
    | '/conditions-generales'
    | '/logistique'
    | '/partenaire'
    | '/solution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  CommercantsRoute: typeof CommercantsRoute
  ConditionsGeneralesRoute: typeof ConditionsGeneralesRoute
  LogistiqueRoute: typeof LogistiqueRoute
  PartenaireRoute: typeof PartenaireRoute
  SolutionRoute: typeof SolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaire': {
      id: '/partenaire'
      path: '/partenaire'
      fullPath: '/partenaire'
      preLoaderRoute: typeof PartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistique': {
      id: '/logistique'
      path: '/logistique'
      fullPath: '/logistique'
      preLoaderRoute: typeof LogistiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales': {
      id: '/conditions-generales'
      path: '/conditions-generales'
      fullPath: '/conditions-generales'
      preLoaderRoute: typeof ConditionsGeneralesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercants': {
      id: '/commercants'
      path: '/commercants'
      fullPath: '/commercants'
      preLoaderRoute: typeof CommercantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  CommercantsRoute: CommercantsRoute,
  ConditionsGeneralesRoute: ConditionsGeneralesRoute,
  LogistiqueRoute: LogistiqueRoute,
  PartenaireRoute: PartenaireRoute,
  SolutionRoute: SolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
